### ISSUE TITLE
As a Erasmus+ candidate, I can add courses offered by the Receiving Institution to the LA

### ISSUE THREAD

**Issue by PKCPablo** [Gregsai/SDS-Mamacita#8]
## Acceptance criteria

- [x] There is a button to add the course to the LA (a circle with a '+' inside)
- [x] When clicked, a confirmation notification will appear
- [x] When you go to the Learning Agreement page, you can see it added to the LA and favourite table

**Comment by Gregsai** [comment]
# Greg

## Branch to test 

greg-test 

Yout might need to delete the branch on your local repo and pull it again since i deleted it and recreated a new one

## Explanation 

When clicking on the plus button, a drop down menu will appear. The user can either : 

- Select the  LA in which he want to add the course. Once it is done, the dropdown closes and the user receive a pop up. The course is also automatically added to the favourite courses. 

- Create a new LA. Once it is done, the user receive a popup and the dropdown menu stays open so that the user can add the course to the la. You still have to be a bit slow. Else some errors might appear

## Video


https://github.com/Gregsai/SDS-Mamacita/assets/85080566/51e5725e-339f-4f79-a068-029dedd5c22e

**Comment by PKCPablo** [comment]
Good work!
